### PR TITLE
Implement hasNotificationsEnabled for android and JARs update

### PR DESCRIPTION
**Pull request by rborn**
This should fix the android side of https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/issues/31 :)

### CODE REVIEW

**Comment by shaders** [comment]
Actually you can just call:
pushManager.isNotificationEnabled(mContext);

The code is there already.

**Comment by rborn** [comment]
Ok, I'll have a look, thank you 😄  It doesn't show up in the docs so I didn't know about 😢

**Comment by DimanAM** [comment]
Implemented in [getNotificationSettings](https://github.com/Pushwoosh/pushwoosh-appcelerator-titanium/tree/master/Documentation#getnotificationsettings)

**Comment by rborn** [comment]
ooo, thank you :) 💪

**Pull request closed without merging**
